backend:
  name: 'git-gateway'
  branch: 'master'
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - label: 'Sidor'
    name: 'pages'
    folder: 'content/pages'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - label: 'Rubrik'
        name: 'title'
        widget: 'string'
      - label: 'Brödtext'
        name: 'body'
        widget: 'markdown'
  - label: 'Diverse'
    name: 'misc'
    editor:
      preview: false
    files:
      - label: 'Navigation'
        name: 'navigation'
        file: 'content/navigation.md'
        fields:
          - label: 'Titel (mobil)'
            name: 'title'
            widget: 'string'
          - label: 'Länkar'
            name: 'items'
            widget: 'list'
            summary: '{{fields.title}}'
            fields:
              - label: 'Rubrik'
                name: 'title'
                widget: 'string'
              - label: 'Beskrivning'
                name: 'description'
                widget: 'string'
              - label: 'Bild'
                name: 'thumbnail'
                widget: 'image'
              - label: 'Länk'
                name: 'link'
                widget: 'relation'
                collection: 'pages'
                search_fields: ['title']
                value_field: '{{slug}}'
                display_fields: ['title']
      - label: 'Veckans meny'
        name: 'week'
        file: 'content/week.md'
        format: 'frontmatter'
        fields:
          - label: 'Titel'
            name: 'title'
            widget: 'string'
          - label: 'Meny'
            name: 'menu'
            widget: 'list'
            summary: '{{fields.weekday}}'
            fields:
              - label: 'Veckodag'
                widget: 'select'
                name: 'weekday'
                options:
                  - { label: 'Måndag', value: '0' }
                  - { label: 'Tisdag', value: '1' }
                  - { label: 'Onsdag', value: '2' }
                  - { label: 'Torsdag', value: '3' }
                  - { label: 'Fredag', value: '4' }
                  - { label: 'Lördag', value: '5' }
                  - { label: 'Söndag', value: '6' }
              - label: 'Rätter'
                name: 'options'
                widget: 'list'
                summary: '{{fields.option}}'
                field:
                  { label: 'Beskrivning', name: 'option', widget: 'string' }
          - { label: 'Brödtext', name: 'body', widget: 'markdown' }
      - label: 'Kontaktinformation'
        name: 'contact'
        file: 'content/contact.md'
        fields:
          - { label: 'Google Maps länk', name: 'address', widget: 'string' }
          - { label: 'Telefonnummer', name: 'phone', widget: 'string' }
          - { label: 'Email', name: 'email', widget: 'string' }
          - { label: 'Facebook länk', name: 'facebook', widget: 'string' }
          - { label: 'Instagram länk', name: 'instagram', widget: 'string' }
